
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int ADDOP = 25;
  public static final int READ = 8;
  public static final int RELOP = 26;
  public static final int ELSE = 4;
  public static final int THEN = 3;
  public static final int SEMI = 29;
  public static final int CHAR = 20;
  public static final int INTEGER_CONST = 12;
  public static final int WHILE = 6;
  public static final int END = 22;
  public static final int IDENTIFIER = 15;
  public static final int TRUE = 11;
  public static final int IF = 2;
  public static final int COLON = 30;
  public static final int MULOP = 28;
  public static final int WRITE = 9;
  public static final int PROGRAM = 16;
  public static final int BEGIN = 21;
  public static final int DO = 5;
  public static final int BOOLEAN = 19;
  public static final int LEFT_PAR = 23;
  public static final int COMMA = 31;
  public static final int EOF = 0;
  public static final int RIGHT_PAR = 24;
  public static final int REAL_CONST = 13;
  public static final int MINUS = 32;
  public static final int FALSE = 10;
  public static final int error = 1;
  public static final int ASSIGN = 27;
  public static final int UNTIL = 7;
  public static final int INTEGER = 17;
  public static final int REAL = 18;
  public static final int CHAR_CONST = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "WHILE",
  "UNTIL",
  "READ",
  "WRITE",
  "FALSE",
  "TRUE",
  "INTEGER_CONST",
  "REAL_CONST",
  "CHAR_CONST",
  "IDENTIFIER",
  "PROGRAM",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "CHAR",
  "BEGIN",
  "END",
  "LEFT_PAR",
  "RIGHT_PAR",
  "ADDOP",
  "RELOP",
  "ASSIGN",
  "MULOP",
  "SEMI",
  "COLON",
  "COMMA",
  "MINUS"
  };
}

